language: node_js

sudo: false

node_js:
- 8

env:
  global:
    - ENV_BUCKET_NAME=newsforyou-bot-config-jhoeke
    - AWS_REGION=eu-central-1

cache: yarn

script:
- echo "No tests :)"

deploy:
  - provider: script
    skip_cleanup: true
    script: export SLS_STAGE=jhoeke && yarn serverless deploy
    on:
      branch: master