language: node_js

sudo: false

node_js:
  - 8

env:
  global:
    - ENV_BUCKET_NAME=newsforyou-bot-config
    - AWS_REGION=eu-central-1

cache: yarn

script:
  - echo "No tests :("
deploy:
  - provider: script
    skip_cleanup: true
    script: export SLS_STAGE=staging && yarn serverless deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: export SLS_STAGE=production && yarn serverless deploy
    on:
      branch: production

notifications:
  slack:
    rooms:
      - secure: k04gHLr2jCikDDkxgh3XIOMS4h+f7OL4Gnao1LpueSFYmL19qp5q9gvtIpMPz7u5yGWQarD/FNoH5xM6Crm/4BLIDYYZtezaSEoRUGGqlGrx4ViTXCUVAlrV3V+8T+4KSJ4lzE0iwY0V3BrqyITHzyURnv3P5TirtyXQnf+HqUKd7AJqPPKswxGpSXVGXOkslzyz+qQsF6rGM31wF7W1fBnzhTmeDtWOlDglKSRnWhInDXfhdUCiEs4un0bmmlNFSo4vtCqa1FTlxbYJxosRFfQ3I1+ozFLdXzhFMjORq0HKjPYz7lygg/SZmEGq8hX/hfzjhi4LFIF3v0KVsmuheXiZeGDZvLn2OgvFC9SoSUSYmZyOW6SFnm5Xm2RCTCV01jYw9t0jY/wyu5dO6upNrEJh+tH5hzclQ/DUspWviAADpH9XQbf3od2U4fIDK3+ZuwXjAxiRg7luB5JRndGScOkcCsulrBzkwlvwPUmanWYDNIehYFmAydrqqZQnRql4LEYRROT5YghY/fCN1cGTNdB4wyPIxsSy2VNypsaHarWfd3UJzwqRHyGvOPub0qAtC9fqeaXrL06AWTCrA6YF4uNWF2EqGFaZ3FutA+IO/rKeu/0JFy7J+r2F2PDrowRCXAiqk1hgynba9+ZJzZTdRqGooxUwZwVhkFXlJ2FC4YY=
    on_pull_requests: false
    template:
      - "Deployment %{result}:"
      - "<%{compare_url}|%{repository_slug}:%{branch}#%{commit}> by %{author}"
